---
services:
  hsd:
    image: handshakeorg/hsd:8.0.0
    container_name: hsd
    network_mode: host
    restart: unless-stopped
    volumes:
      - $HOME/.hsd:/root/.hsd
    command: >
      --network main
      --spv
      --http-host 0.0.0.0
      --api-key=your_node_api_key
      --wallet-http-host=0.0.0.0
      --wallet-api-key=your_wallet_api_key

  teleshake:
    image: skywirex/teleshake:v0.5.0
    container_name: teleshake
    network_mode: host
    depends_on:
      - hsd
    restart: unless-stopped
    volumes:
      - $HOME/docker/teleshake/config.json:/app/config.json
    # 3-second delay after hsd starts
    entrypoint: ["/bin/sh", "-c", "sleep 3 && exec /app/scripts/teleshake.sh"]
    environment:
      - LOOP_SECONDS=3600   # or whatever interval you want
